
word = [ 'abelha',
        'atum',
        'asa',
        'abacaxi',
        'acesso',
        'acorde',

        'banguela',
        'balde',
        'banco',
        'banda',
        'batalha',
        'batata',

        'casa',
        'campo',
        'camisa',
        'cana',
        'careca',
        'carta',

        'delta',
        'deputado',
        'descolar',
        'destruidor',
        'dicionario',
        'diesel',

        'embora',
        'empresa',
        'encanador',
        'escorregar',
        'escudo',
        'esmola',

        'falar',
        'falido',
        'facismo',
        'fatura',
        'favela',
        'favor',

        'gigante',
        'gaveta',
        'gincana',
        'gaita',
        'galera',
        'garrafa',

        'habilidoso',
        'heroico',
        'hesitar',
        'harmonia',
        'horizontal',
        'horror',

        'igreja',
        'igualdade',
        'internet',
        'ilha',
        'impedir',
        'impacto'
        
        'jubileu',
        'judoca',
        'julgar',
        'jejum',
        'jato',
        'janta',

        'kamikaze',
        'kiwi',
        'kit',
        'kart',

        'lindo',
        'labial',
        'lamina',
        'laranja',
        'lugar',
        'lagosta',

        'macaco',
        'marta',
        'marte',
        'mascara',
        'maratona',
        'marido',

        'napa',
        'naja',
        'natureza',
        'navalia',
        'nave',
        'necessidade',
        'nevar'

        'obrigado',
        'objeto',
        'oculto',
        'odor',
        'ouvido',
        'ovelha',

        'padre',
        'padrasto',
        'pagode',
        'pai',
        'pacu',
        'passado',
        'peixe',

        'quadra',
        'quantia',
        'quadrilha',
        'quebrada',
        'queimar',
        'quente',
        'questionar',

        'rato',
        'ratazana',
        'rascunho',
        'ramo',
        'revigorar',
        'rio',

        'selva',
        'sagrado',
        'salva',
        'sangue',
        'sereia',
        'setor',

        'talento',
        'tanga',
        'tanque',
        'tarjeta',
        'termino',
        'temporal',

        'ucraniano',
        'ultraje',
        'umbanda',
        'urbano',
        'urina',
        'urso',

        'vaca',
        'valsa',
        'vapor',
        'varrer',
        'vazio',
        'venezuela',

        'windows',
        'wagner',
        'wesley',
        'web',

        'xuxa',
        'xadrez',
        'xeque',
        'xerife',
        'xixi',
        'xilindro',

        'zabumda',
        'zero',
        'zerar',
        'zebra',
        'zona',
        'zumbi',
        'zorra',]